const countryArray = [
    { countryName: "United Arab Emirates", countryCode: "ae" },
    { countryName: "Argentina", countryCode: "ar" },
    { countryName: "Austria", countryCode: "at" },
    { countryName: "Australia", countryCode: "au" },
    { countryName: "Belgium", countryCode: "be" },
    { countryName: "Bulgaria", countryCode: "bg" },
    { countryName: "Brazil", countryCode: "br" },
    { countryName: "Canada", countryCode: "ca" },
    { countryName: "Switzerland", countryCode: "ch" },
    { countryName: "China", countryCode: "cn" },
    { countryName: "Colombia", countryCode: "co" },
    { countryName: "Cuba", countryCode: "cu" },
    { countryName: "Czechia", countryCode: "cz" },
    { countryName: "Germany", countryCode: "de" },
    { countryName: "Egypt", countryCode: "eg" },
    { countryName: "France", countryCode: "fr" },
    { countryName: "United Kingdom", countryCode: "gb" },
    { countryName: "Greece", countryCode: "gr" },
    { countryName: "Hong Kong", countryCode: "hk" },
    { countryName: "Hungary", countryCode: "hu" },
    { countryName: "Indonesia", countryCode: "id" },
    { countryName: "Ireland", countryCode: "ie" },
    { countryName: "Israel", countryCode: "il" },
    { countryName: "India", countryCode: "in" },
    { countryName: "Italy", countryCode: "it" },
    { countryName: "Japan", countryCode: "jp" },
    { countryName: "South Korea", countryCode: "kr" },
    { countryName: "Lithuania", countryCode: "lt" },
    { countryName: "Latvia", countryCode: "lv" },
    { countryName: "Morocco", countryCode: "ma" },
    { countryName: "Mexico", countryCode: "mx" },
    { countryName: "Malaysia", countryCode: "my" },
    { countryName: "Nigeria", countryCode: "ng" },
    { countryName: "Netherlands", countryCode: "nl" },
    { countryName: "Norway", countryCode: "no" },
    { countryName: "New Zealand", countryCode: "nz" },
    { countryName: "Philippines", countryCode: "ph" },
    { countryName: "Poland", countryCode: "pl" },
    { countryName: "Portugal", countryCode: "pt" },
    { countryName: "Romania", countryCode: "ro" },
    { countryName: "Serbia", countryCode: "rs" },
    { countryName: "Russia", countryCode: "ru" },
    { countryName: "Saudi Arabia", countryCode: "sa" },
    { countryName: "Sweden", countryCode: "se" },
    { countryName: "Singapore", countryCode: "sg" },
    { countryName: "Slovenia", countryCode: "si" },
    { countryName: "Slovakia", countryCode: "sk" },
    { countryName: "Thailand", countryCode: "th" },
    { countryName: "Turkey", countryCode: "tr" },
    { countryName: "Taiwan", countryCode: "tw" },
    { countryName: "Ukraine", countryCode: "ua" },
    { countryName: "United States", countryCode: "us" },
    { countryName: "Venezuela", countryCode: "ve" },
    { countryName: "South Africa", countryCode: "za" },
    { countryName: "American Samoa", countryCode: "as" },
    { countryName: "Spain", countryCode: "es" },
    { countryName: "South Georgia", countryCode: "gs" },
    { countryName: "Iceland", countryCode: "is" },
    { countryName: "Cambodia", countryCode: "kh" }
  ];
export default countryArray;  